# hugo.toml

baseURL = "https://raphaelfranco.dev/"
languageCode = "pt-BR"
title = "Raphael Franco | Data Engineer"
theme = ""
enableRobotsTXT = true

[params]
  description = "Portf√≥lio de Engenharia de Dados e Business Intelligence."
  author = "Raphael Franco"
  logoTitle = "Raphael Franco"

[outputs]
  home = ["HTML", "RSS"]