baseURL = "https://raphamaster.github.io/site-portfolio/"
languageCode = "pt-BR"
title = "Raphael Franco | Data Engineer"
enableRobotsTXT = true

[params]
  description = "Portf√≥lio de Engenharia de Dados e Business Intelligence."
  logoTitle = "DataEngineer"

  # AUTOR DENTRO DE PARAMS (Formato Moderno)
  # Isso cria um objeto .Site.Params.author com campos name e email
  [params.author]
    name = "Raphael Franco"
    email = "raphael@exemplo.com"

[outputs]
  home = ["HTML", "RSS"]