# hugo.toml

baseURL = "https://raphamaster.github.io/site-portfolio/"
languageCode = "pt-BR"
title = "Raphael Franco | Data Engineer"
enableRobotsTXT = true

[author]
  name = "Raphael Franco"
  email = "contato@raphaelfranco.com"

[params]
  description = "Portf√≥lio de Engenharia de Dados e Business Intelligence."
  author = "Raphael Franco"
  logoTitle = "Raphael Franco"

[outputs]
  home = ["HTML", "RSS"]