baseURL = "https://raphamaster.github.io/site-portfolio/"
languageCode = "pt-BR"
title = "Raphael Franco | Data Engineer"
enableRobotsTXT = true

# CONFIGURAÇÃO OFICIAL DE AUTOR
# O Hugo usa isso para o RSS e nós usaremos para o Rodapé também.
[author]
  name = "Raphael Franco"
  email = "raphael@exemplo.com"

[params]
  description = "Portfólio de Engenharia de Dados e Business Intelligence."
  logoTitle = "DataEngineer"
  # Removemos a linha 'author' daqui para não causar conflito.

[outputs]
  home = ["HTML", "RSS"]